version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@1.8.2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/repo
    steps:
      - checkout
      - gcp-cli/initialize
      - run: gcloud kms decrypt --location global --keyring env --key tokens --plaintext-file secret.yaml --ciphertext-file secret.yaml.enc
      - run: gcloud --quiet app deploy
